### ISSUE TITLE
-1 | --first option

### ISSUE THREAD

**Issue by fazibear** [nofxx/subtitle_it#10]
Options to get the first one without asking. It will be helpful to process multiple files.

**Comment by nofxx** [comment]
Either that or a ~/.subtitle_it  with your default (or maybe multiple) languages wanted.
What do you think?

**Comment by fazibear** [comment]
I think option is better. `-f` is force options, `-1 | --first` is nice. File with defaults will contains only wanted languages. I think its not necessary.
